[package]
name = "rimmy_proc"
version = "0.1.0"
edition = "2024"

[features]
test = []
default = []

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
proc-macro-error = "1.0.4"
quote = "1"
proc-macro-crate = "3"

[dependencies.syn]
features = ["full"]
version = "1.0.91"
